### ISSUE TITLE
Versions 3.14.0 and 3.14.1 not downloading

### ISSUE THREAD

**Issue by demonar** [ROKT/rokt-sdk-ios#24]
binary versions 3.14.0 and 3.14.1 are not working, getting an error from amazon

**Comment by demonar** [comment]
`https://rokt-eng-us-west-2-mobile-sdk-artefacts.s3.amazonaws.com/ios/3.14.0/Rokt_Widget.xcframework.zip`

returns:

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>ios/3.14.0/Rokt_Widget.xcframework.zip</Key>
<RequestId>3SDPKQNB5ACBAF8F</RequestId>
<HostId>FaGKLARYhfS7GnFDcaey4HoKYKHpgd1lNMVYRlw6k0pAqpUBtWQ6C+RPqVlSy1ssm5hz8GJQicI=</HostId>
</Error>`

**Comment by demonar** [comment]
`https://rokt-eng-us-west-2-mobile-sdk-artefacts.s3.amazonaws.com/ios/3.14.1/Rokt_Widget.xcframework.zip`

returns:

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>ios/3.14.1/Rokt_Widget.xcframework.zip</Key>
<RequestId>D6EG0JFPGE3MNETX</RequestId>
<HostId>9HHOdsyaBlXCbFqBhccs0FExuGxlXu+38aUjgD0exXHYJODHVNJJWzzYcvqPzffxpSMiKtJ1kJY=</HostId>
</Error>`

**Comment by emmanuel-rokt** [comment]
can you try the latest version of our SDK, 3.15.6, instead? thank you
