### ISSUE TITLE
Privacy manifest files

### ISSUE THREAD

**Issue by hatched-tomasz** [ROKT/rokt-sdk-ios#42]
Apple introduced a document that needs to be provided to the SDK - Privacy Manifest (https://developer.apple.com/documentation/bundleresources/privacy_manifest_files). When can we expect the library to be updated with this document?

**Comment by tomaszpluciennik-tomtom** [comment]
Ok I found https://docs.rokt.com/developers/integration-guides/ios/reference/version version 4.2.0 contains privacy manifest

**Comment by danial-rokt** [comment]
Hi @hatched-tomasz 

Thank you for reaching out. I believe the details about the privacy manifest have already been shared with you. Starting with SDK version 4.2.0, the privacy manifest has been included in the XCFramework of the Rokt SDK. For more information, please refer to [this page](https://docs.rokt.com/developers/integration-guides/ios/reference/privacy).
